// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package generated_sqlite

import (
	"context"
	"database/sql"
)

const createProjectRecord = `-- name: CreateProjectRecord :one
insert into projects (name, description, git_branch)
values (?, ?, ?)
returning id, name, description, created_at, updated_at, git_branch
`

type CreateProjectRecordParams struct {
	Name        string
	Description sql.NullString
	GitBranch   interface{}
}

// Creates a new project with name and description
func (q *Queries) CreateProjectRecord(ctx context.Context, arg CreateProjectRecordParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProjectRecord, arg.Name, arg.Description, arg.GitBranch)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitBranch,
	)
	return i, err
}

const deleteColumnsByProject = `-- name: DeleteColumnsByProject :exec
delete from columns
where project_id = ?
`

// Deletes all columns belonging to a project
func (q *Queries) DeleteColumnsByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteColumnsByProject, projectID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
delete from projects where id = ?
`

// Permanently deletes a project by ID
func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteProjectCounter = `-- name: DeleteProjectCounter :exec
delete from project_counters where project_id = ?
`

// Deletes the task counter for a project
func (q *Queries) DeleteProjectCounter(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectCounter, projectID)
	return err
}

const deleteTasksByProject = `-- name: DeleteTasksByProject :exec
delete from tasks
where column_id in (select id from columns where project_id = ?)
`

// Deletes all tasks belonging to a project
func (q *Queries) DeleteTasksByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByProject, projectID)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
select id, name, description, git_branch, created_at, updated_at from projects order by id
`

type GetAllProjectsRow struct {
	ID          int64
	Name        string
	Description sql.NullString
	GitBranch   interface{}
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// Retrieves all projects ordered by ID
func (q *Queries) GetAllProjects(ctx context.Context) ([]GetAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllProjectsRow{}
	for rows.Next() {
		var i GetAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GitBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByGitBranch = `-- name: GetProjectByGitBranch :one
select
    id,
    name,
    description,
    git_branch,
    created_at,
    updated_at
from projects where git_branch = ?
`

type GetProjectByGitBranchRow struct {
	ID          int64
	Name        string
	Description sql.NullString
	GitBranch   interface{}
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// Retrieves a project by its git branch
func (q *Queries) GetProjectByGitBranch(ctx context.Context, gitBranch interface{}) (GetProjectByGitBranchRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByGitBranch, gitBranch)
	var i GetProjectByGitBranchRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GitBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
select
    id,
    name,
    description,
    git_branch,
    created_at,
    updated_at
from projects where id = ?
`

type GetProjectByIDRow struct {
	ID          int64
	Name        string
	Description sql.NullString
	GitBranch   interface{}
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// Retrieves a project by its ID with all metadata
func (q *Queries) GetProjectByID(ctx context.Context, id int64) (GetProjectByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GitBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTaskCount = `-- name: GetProjectTaskCount :one
select count(*)
from tasks t
join columns c on t.column_id = c.id
where c.project_id = ?
`

// Returns the total number of tasks in a project
func (q *Queries) GetProjectTaskCount(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProjectTaskCount, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const initializeProjectCounter = `-- name: InitializeProjectCounter :exec
insert into project_counters (project_id, next_task_number) values (?, 1)
`

// Initializes the task number counter for a new project starting at 1
func (q *Queries) InitializeProjectCounter(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, initializeProjectCounter, projectID)
	return err
}

const updateProject = `-- name: UpdateProject :exec
update projects set name = ?,
description = ?,
git_branch = ?,
updated_at = current_timestamp where id = ?
`

type UpdateProjectParams struct {
	Name        string
	Description sql.NullString
	GitBranch   interface{}
	ID          int64
}

// Updates a project's name and description
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.GitBranch,
		arg.ID,
	)
	return err
}
