// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standup_logs.sql

package generated_sqlite

import (
	"context"
)

const createStandupLog = `-- name: CreateStandupLog :one
insert into standup_logs (project_id, content)
values (?, ?)
returning id, project_id, content, created_at
`

type CreateStandupLogParams struct {
	ProjectID int64
	Content   string
}

// Creates a new standup log entry for a project
func (q *Queries) CreateStandupLog(ctx context.Context, arg CreateStandupLogParams) (StandupLog, error) {
	row := q.db.QueryRowContext(ctx, createStandupLog, arg.ProjectID, arg.Content)
	var i StandupLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStandupLog = `-- name: DeleteStandupLog :exec
delete from standup_logs where id = ?
`

// Deletes a standup log by ID
func (q *Queries) DeleteStandupLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStandupLog, id)
	return err
}

const getStandupLog = `-- name: GetStandupLog :one
select id, project_id, content, created_at
from standup_logs
where id = ?
`

// Retrieves a single standup log by ID
func (q *Queries) GetStandupLog(ctx context.Context, id int64) (StandupLog, error) {
	row := q.db.QueryRowContext(ctx, getStandupLog, id)
	var i StandupLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getStandupLogsByProject = `-- name: GetStandupLogsByProject :many
select id, project_id, content, created_at
from standup_logs
where project_id = ?
order by created_at desc
`

// Retrieves all standup logs for a project, ordered by creation time (newest first)
func (q *Queries) GetStandupLogsByProject(ctx context.Context, projectID int64) ([]StandupLog, error) {
	rows, err := q.db.QueryContext(ctx, getStandupLogsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StandupLog{}
	for rows.Next() {
		var i StandupLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
