version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - tparallel
    - unused
    - whitespace
  disable:
    - sqlclosecheck      # Disabled: using closeRows helper that properly handles closure

run:
  timeout: 5m
