package cli_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/require"
	"github.com/thenoetrevino/paso/internal/cli/assignee"
	"github.com/thenoetrevino/paso/internal/cli/column"
	"github.com/thenoetrevino/paso/internal/cli/db"
	"github.com/thenoetrevino/paso/internal/cli/install"
	"github.com/thenoetrevino/paso/internal/cli/label"
	"github.com/thenoetrevino/paso/internal/cli/project"
	"github.com/thenoetrevino/paso/internal/cli/task"
	"github.com/thenoetrevino/paso/internal/testing/fixtures"
	"github.com/thenoetrevino/paso/internal/testing/snapshots"
)

// buildRootCmd reconstructs the full paso command tree for testing.
// This mirrors main.go's init() without requiring access to unexported symbols.
func buildRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:   "paso",
		Short: "Terminal-based Kanban board with CLI and TUI",
		Long: `Paso is a zero-setup, terminal-based kanban board for personal task management.

Use 'paso tui' to launch the interactive TUI.
Use 'paso task create ...' for CLI commands.`,
	}

	root.AddCommand(task.TaskCmd())
	root.AddCommand(project.ProjectCmd())
	root.AddCommand(column.ColumnCmd())
	root.AddCommand(label.LabelCmd())
	root.AddCommand(assignee.AssigneeCmd())
	root.AddCommand(install.InstallCmd())
	root.AddCommand(db.DbCmd())

	root.AddCommand(&cobra.Command{
		Use:   "tui",
		Short: "Launch the interactive TUI",
		Long:  "Launch the interactive terminal user interface for managing tasks visually.",
	})

	root.AddCommand(&cobra.Command{
		Use:   "completion [bash|zsh|fish|powershell]",
		Short: "Generate shell completion script",
		Long: `Generate shell completion script for paso.

To load completions:

Bash:
  $ source <(paso completion bash)

  # To load completions for each session, execute once:
  # Linux:
  $ paso completion bash > /etc/bash_completion.d/paso
  # macOS:
  $ paso completion bash > $(brew --prefix)/etc/bash_completion.d/paso

Zsh:
  # If shell completion is not already enabled in your environment,
  # you will need to enable it. You can execute the following once:
  $ echo "autoload -U compinit; compinit" >> ~/.zshrc

  # To load completions for each session, execute once:
  $ paso completion zsh > "${fpath[1]}/_paso"

  # You will need to start a new shell for this setup to take effect.

Fish:
  $ paso completion fish | source

  # To load completions for each session, execute once:
  $ paso completion fish > ~/.config/fish/completions/paso.fish

PowerShell:
  PS> paso completion powershell | Out-String | Invoke-Expression

  # To load completions for every new session, run:
  PS> paso completion powershell > paso.ps1
  # and source this file from your PowerShell profile.
`,
		DisableFlagsInUseLine: true,
		ValidArgs:             []string{"bash", "zsh", "fish", "powershell"},
	})

	return root
}

type commandEntry struct {
	name string
	cmd  *cobra.Command
}

// collectCommands recursively walks a cobra command tree and returns every
// command with a dash-joined path name (e.g. "task", "task-create").
// Cobra auto-generates "help" and "completion" children on every parent;
// we skip those to only snapshot our own commands.
func collectCommands(cmd *cobra.Command, prefix string) []commandEntry {
	name := cmd.Name()
	if prefix != "" {
		name = prefix + "-" + name
	}

	entries := []commandEntry{{name: name, cmd: cmd}}

	for _, child := range cmd.Commands() {
		if isAutoGenerated(child) {
			continue
		}
		entries = append(entries, collectCommands(child, name)...)
	}

	return entries
}

// isAutoGenerated returns true for commands that Cobra adds automatically
// to every parent (help, completion and its shell-specific children).
func isAutoGenerated(cmd *cobra.Command) bool {
	switch cmd.Name() {
	case "help", "completion":
		// Skip only if this looks auto-generated (no Long description we wrote).
		// Our root-level "completion" command has a Long description with "paso".
		if cmd.Long == "" || !strings.Contains(cmd.Long, "paso") {
			return true
		}
	}
	return false
}

func captureHelpOutput(t *testing.T, cmd *cobra.Command) string {
	t.Helper()
	var buf bytes.Buffer
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)

	err := cmd.Help()
	require.NoError(t, err, "help command should not error")

	return fixtures.StripANSI(buf.String())
}

func TestGolden_HelpOutput(t *testing.T) {
	root := buildRootCmd()
	commands := collectCommands(root, "")

	for _, entry := range commands {
		t.Run(entry.name, func(t *testing.T) {
			// Build a fresh command tree per subtest so SetArgs doesn't bleed
			freshRoot := buildRootCmd()
			target := findCommand(t, freshRoot, entry.name)

			output := captureHelpOutput(t, target)
			helper := snapshots.NewHelper(t, "testdata/help")
			helper.Compare(entry.name, output)
		})
	}
}

// findCommand locates a command in the tree by its dash-joined path name.
// e.g. "task-create" finds root -> task -> create.
func findCommand(t *testing.T, root *cobra.Command, name string) *cobra.Command {
	t.Helper()

	// Root command
	if name == root.Name() {
		return root
	}

	// Strip the root prefix: "paso-task-create" -> "task-create"
	prefix := root.Name() + "-"
	if !strings.HasPrefix(name, prefix) {
		t.Fatalf("command name %q does not start with root prefix %q", name, prefix)
	}
	remaining := strings.TrimPrefix(name, prefix)

	parts := strings.SplitN(remaining, "-", 2)
	for _, child := range root.Commands() {
		if child.Name() == parts[0] {
			if len(parts) == 1 {
				return child
			}
			return findSubCommand(t, child, parts[1])
		}
	}

	t.Fatalf("command %q not found in command tree", name)
	return nil
}

// findSubCommand navigates deeper levels using the remaining dash-joined path.
func findSubCommand(t *testing.T, parent *cobra.Command, remaining string) *cobra.Command {
	t.Helper()

	parts := strings.SplitN(remaining, "-", 2)
	for _, child := range parent.Commands() {
		if child.Name() == parts[0] {
			if len(parts) == 1 {
				return child
			}
			return findSubCommand(t, child, parts[1])
		}
	}

	// Some commands use hyphens in their name (e.g. "in-progress", "to-ready",
	// "git-link"). If a simple split didn't match, try matching the full
	// remaining string as a single command name.
	for _, child := range parent.Commands() {
		if child.Name() == remaining {
			return child
		}
	}

	t.Fatalf("subcommand %q not found under %q", remaining, parent.Name())
	return nil
}
