-- +goose Up
-- Initial schema for paso task management system (PostgreSQL version)

-- Lookup table for task types
create table types (
    id bigint primary key generated by default as identity,
    description text not null unique
);

insert into types (id, description) values
    (1, 'task'),
    (2, 'feature'),
    (3, 'bug');

-- Update sequence for types table
select setval('types_id_seq', (select max(id) from types));

-- Lookup table for task priorities
create table priorities (
    id bigint primary key generated by default as identity,
    description text not null unique,
    color text not null
);

insert into priorities (id, description, color) values
    (1, 'trivial', '#3b82f6'),
    (2, 'low', '#22c55e'),
    (3, 'medium', '#eab308'),
    (4, 'high', '#f97316'),
    (5, 'critical', '#ef4444');

-- Update sequence for priorities table
select setval('priorities_id_seq', (select max(id) from priorities));

-- Lookup table for task relationship types
create table relation_types (
    id bigint primary key generated by default as identity,
    p_to_c_label text not null,
    c_to_p_label text not null,
    color text not null,
    is_blocking boolean not null default false
);

insert into relation_types (id,
p_to_c_label,
c_to_p_label,
color,
is_blocking) values
    (1, 'Parent', 'Child', '#6B7280', false),
    (2, 'Blocked By', 'Blocker', '#EF4444', true),
    (3, 'Related To', 'Related To', '#3B82F6', false);

-- Update sequence for relation_types table
select setval('relation_types_id_seq', (select max(id) from relation_types));

-- Projects table
create table projects (
    id bigint primary key generated by default as identity,
    name text not null,
    description text default '',
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp
);

-- Project ticket number counters
create table project_counters (
    project_id bigint primary key,
    next_ticket_number bigint default 1,
    foreign key (project_id) references projects(id) on delete cascade
);

-- Columns table (linked list structure for board columns)
create table columns (
    id bigint primary key generated by default as identity,
    name text not null,
    prev_id bigint null,
    next_id bigint null,
    project_id bigint not null,
    holds_ready_tasks boolean not null default false,
    holds_completed_tasks boolean not null default false,
    holds_in_progress_tasks boolean not null default false,
    foreign key (project_id) references projects(id) on delete cascade
);

-- Labels table
create table labels (
    id bigint primary key generated by default as identity,
    name text not null,
    color text not null default '#7D56F4',
    project_id bigint not null,
    foreign key (project_id) references projects(id) on delete cascade,
    unique(name, project_id)
);

-- Tasks table
create table tasks (
    id bigint primary key generated by default as identity,
    title text not null,
    description text,
    column_id bigint not null,
    position bigint not null,
    ticket_number bigint,
    type_id bigint not null default 1,
    priority_id bigint not null default 3,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp,
    foreign key (column_id) references columns(id) on delete cascade,
    foreign key (type_id) references types(id),
    foreign key (priority_id) references priorities(id)
);

-- Task-labels many-to-many relationship
create table task_labels (
    task_id bigint not null,
    label_id bigint not null,
    primary key (task_id, label_id),
    foreign key (task_id) references tasks(id) on delete cascade,
    foreign key (label_id) references labels(id) on delete cascade
);

-- Task relationships (parent-child, blocking, etc.)
create table task_subtasks (
    parent_id bigint not null,
    child_id bigint not null,
    relation_type_id bigint not null default 1,
    primary key (parent_id, child_id),
    foreign key (parent_id) references tasks(id) on delete cascade,
    foreign key (child_id) references tasks(id) on delete cascade,
    foreign key (relation_type_id) references relation_types(id)
);

-- Task comments/notes
create table task_comments (
    id bigint primary key generated by default as identity,
    task_id bigint not null,
    content text not null check(length(content) <= 1000),
    author text not null default '',
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp,
    foreign key (task_id) references tasks(id) on delete cascade
);

-- Indexes for performance
create index idx_tasks_column on tasks(column_id, position);
create index idx_columns_project on columns(project_id);
create index idx_labels_project on labels(project_id);
create index idx_task_labels_label on task_labels(label_id);
create index idx_task_subtasks_parent on task_subtasks(parent_id);
create index idx_task_subtasks_child on task_subtasks(child_id);
create index idx_task_comments_task on task_comments(task_id);

-- Unique partial indexes for column constraints
create unique index idx_columns_ready_per_project 
    on columns(project_id) where holds_ready_tasks = true;
create unique index idx_columns_completed_per_project 
    on columns(project_id) where holds_completed_tasks = true;
create unique index idx_columns_in_progress_per_project 
    on columns(project_id) where holds_in_progress_tasks = true;

-- +goose Down
-- Drop all tables and indexes in reverse order

drop index if exists idx_columns_in_progress_per_project;
drop index if exists idx_columns_completed_per_project;
drop index if exists idx_columns_ready_per_project;
drop index if exists idx_task_comments_task;
drop index if exists idx_task_subtasks_child;
drop index if exists idx_task_subtasks_parent;
drop index if exists idx_task_labels_label;
drop index if exists idx_labels_project;
drop index if exists idx_columns_project;
drop index if exists idx_tasks_column;

drop table if exists task_comments;
drop table if exists task_subtasks;
drop table if exists task_labels;
drop table if exists tasks;
drop table if exists labels;
drop table if exists columns;
drop table if exists project_counters;
drop table if exists projects;
drop table if exists relation_types;
drop table if exists priorities;
drop table if exists types;
