// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignees.sql

package generated_postgres

import (
	"context"
)

const createAssignee = `-- name: CreateAssignee :one
insert into assignees (name)
values ($1)
returning id, name, created_at, updated_at
`

// Creates a new assignee
func (q *Queries) CreateAssignee(ctx context.Context, name string) (Assignee, error) {
	row := q.db.QueryRowContext(ctx, createAssignee, name)
	var i Assignee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignee = `-- name: DeleteAssignee :execrows
delete from assignees
where id = $1
`

// Deletes an assignee by ID
// Note: Tasks will have assignee_id set to null via on delete set null
func (q *Queries) DeleteAssignee(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAssignee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAssigneeByID = `-- name: GetAssigneeByID :one
select id, name, created_at, updated_at
from assignees
where id = $1
`

// Retrieves an assignee by ID
func (q *Queries) GetAssigneeByID(ctx context.Context, id int32) (Assignee, error) {
	row := q.db.QueryRowContext(ctx, getAssigneeByID, id)
	var i Assignee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssigneeByName = `-- name: GetAssigneeByName :one
select id, name, created_at, updated_at
from assignees
where lower(name) = lower($1)
`

// Retrieves an assignee by name (case-insensitive)
func (q *Queries) GetAssigneeByName(ctx context.Context, lower string) (Assignee, error) {
	row := q.db.QueryRowContext(ctx, getAssigneeByName, lower)
	var i Assignee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignees = `-- name: ListAssignees :many
select id, name, created_at, updated_at
from assignees
order by name
`

// Lists all assignees ordered by name
func (q *Queries) ListAssignees(ctx context.Context) ([]Assignee, error) {
	rows, err := q.db.QueryContext(ctx, listAssignees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignee{}
	for rows.Next() {
		var i Assignee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
