// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package generated_postgres

import (
	"database/sql"
)

type Assignee struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Column struct {
	ID                   int64
	Name                 string
	PrevID               sql.NullInt64
	NextID               sql.NullInt64
	ProjectID            int64
	HoldsReadyTasks      bool
	HoldsCompletedTasks  bool
	HoldsInProgressTasks bool
}

type Label struct {
	ID        int64
	Name      string
	Color     string
	ProjectID int64
}

type Priority struct {
	ID          int64
	Description string
	Color       string
}

type Project struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	GitBranch   sql.NullString
}

type ProjectCounter struct {
	ProjectID        int64
	NextTicketNumber sql.NullInt64
}

type RelationType struct {
	ID         int64
	PToCLabel  string
	CToPLabel  string
	Color      string
	IsBlocking bool
}

type Task struct {
	ID           int64
	Title        string
	Description  sql.NullString
	ColumnID     int64
	Position     int64
	TicketNumber sql.NullInt64
	TypeID       int64
	PriorityID   int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	AssigneeID   sql.NullInt32
	Estimate     sql.NullString
}

type TaskComment struct {
	ID        int64
	TaskID    int64
	Content   string
	Author    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TaskEvent struct {
	ID        int64
	TaskID    int64
	Content   string
	Author    string
	CreatedAt sql.NullTime
}

type TaskLabel struct {
	TaskID  int64
	LabelID int64
}

type TaskSubtask struct {
	ParentID       int64
	ChildID        int64
	RelationTypeID int64
}

type Type struct {
	ID          int64
	Description string
}
