// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_events.sql

package generated_postgres

import (
	"context"
)

const createTaskEvent = `-- name: CreateTaskEvent :one
insert into task_events (task_id, content, author)
values ($1, $2, $3)
returning id, task_id, content, author, created_at
`

type CreateTaskEventParams struct {
	TaskID  int64
	Content string
	Author  string
}

// Creates a new event for a task
func (q *Queries) CreateTaskEvent(ctx context.Context, arg CreateTaskEventParams) (TaskEvent, error) {
	row := q.db.QueryRowContext(ctx, createTaskEvent, arg.TaskID, arg.Content, arg.Author)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEventsByTask = `-- name: DeleteEventsByTask :exec
delete from task_events where task_id = $1
`

// Deletes all events for a task (for testing/cleanup)
func (q *Queries) DeleteEventsByTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventsByTask, taskID)
	return err
}

const getEventsByTask = `-- name: GetEventsByTask :many
select id, task_id, content, author, created_at
from task_events
where task_id = $1
order by created_at desc
`

// Retrieves all events for a task, ordered by creation time (newest first)
func (q *Queries) GetEventsByTask(ctx context.Context, taskID int64) ([]TaskEvent, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
